services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - ${MARIADB_PORT:-3306}:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - UPLOAD_LIMIT=${LIMITE_UPLOAD_SIZE}
      - MAX_EXECUTION_TIME=${LIMITE_TIMEOUT_PHP}
      - MEMORY_LIMIT=${LIMITE_MEMORIA}
    volumes:
      - phpmyadmin_sessions:/sessions

volumes:
  mariadb_data:
  phpmyadmin_sessions:
